services:
  postgres:
    container_name: postgresdbContainer
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dbname
      PGDATA: /data/postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: